# Generated by Django 5.1.1 on 2025-08-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_products_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(default='home', max_length=100),
            preserve_default=False,
        ),
    ]
